[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'php82Extensions.pdo_mysql']

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader']

[phases.build]
cmds = ['php artisan view:cache']

[start]
cmd = 'bash start.sh'
